apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: psa-test
  name: psa-test
  namespace: psa-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psa-test
  strategy: {}
  template:
    metadata:
      labels:
        app: psa-test
    spec:
      securityContext:
        runAsNonRoot: true
        # Do not use SeccompProfile if your project must work on 
        # old k8s versions < 1.19 and Openshift < 4.11 
        seccompProfile:
          type: RuntimeDefault
      containers:
      - command:
        - nginx
        - -g
        - daemon off;
        image: ubi8/nginx-120
        name: nginx-120
        ports:
        - containerPort: 8080
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: 
              - ALL
